[project]
name = "roserer"
version = "0.1.0"
description = "Model ROS2 systems in python and perform end-to-end real time latency model checking."
readme = "README.md"
authors = [
    { name = "Marcus Skjold", email = "marcusskjold@gmail.com" },
    { name = "Andreas Riget Bagge" }
]
requires-python = ">=3.10"
dependencies = [
    "dataclasses>=0.8",
    "importlib-resources>=6.5.2",
    "ruamel-yaml>=0.19.1",
]

[build-system]
requires = ["uv_build>=0.9.24,<0.10.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = "src"

[tool.ruff]
line-length = 88
extend-select = ["E501", "E305"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.14.13",
    "ty>=0.0.12",
]
